;; Configuration file generated by Emacs Lisp

;; Start startup-performance
;; The default is 800 kilobytes. Measured in bytes.
(setq gc-cons-threshold (* 50 1000 1000))
;; End startup-performance
;; Start elpaca
(defvar elpaca-installer-version 0.7)
(defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
(defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
(defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
(defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                              :ref nil :depth 1
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
(let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
       (build (expand-file-name "elpaca/" elpaca-builds-directory))
       (order (cdr elpaca-order))
       (default-directory repo))
  (add-to-list 'load-path (if (file-exists-p build) build repo))
  (unless (file-exists-p repo)
    (make-directory repo t)
    (when (< emacs-major-version 28) (require 'subr-x))
    (condition-case-unless-debug err
        (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                 ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                 ,@(when-let ((depth (plist-get order :depth)))
                                                     (list (format "--depth=%d" depth) "--no-single-branch"))
                                                 ,(plist-get order :repo) ,repo))))
                 ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                 (emacs (concat invocation-directory invocation-name))
                 ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                 ((require 'elpaca))
                 ((elpaca-generate-autoloads "elpaca" repo)))
            (progn (message "%s" (buffer-string)) (kill-buffer buffer))
          (error "%s" (with-current-buffer buffer (buffer-string))))
      ((error) (warn "%s" err) (delete-directory repo 'recursive))))
  (unless (require 'elpaca-autoloads nil t)
    (require 'elpaca)
    (elpaca-generate-autoloads "elpaca" repo)
    (load "./elpaca-autoloads")))
(add-hook 'after-init-hook #'elpaca-process-queues)
(elpaca `(,@elpaca-order))

(setq elpaca-queue-limit 12) ;; to avoid "too many open files" errors
(elpaca transient)
(elpaca magit)

;; Install use-package support
(elpaca elpaca-use-package
  ;; Enable :elpaca use-package keyword.
  (elpaca-use-package-mode)
  ;; Assume :elpaca t unless otherwise specified.
  (setq elpaca-use-package-by-default t))

;; Block until current queue processed.
(elpaca-wait)

;;When installing a package which modifies a form used at the top-level
;;(e.g. a package which adds a use-package key word),
;;use `elpaca-wait' to block until that package has been installed/configured.
;;For example:
;;(use-package general :demand t)
;;(elpaca-wait)

;;Turns off elpaca-use-package-mode current declartion
;;Note this will cause the declaration to be interpreted immediately (not deferred).
;;Useful for configuring built-in emacs features.
;;(use-package emacs :elpaca nil :config (setq ring-bell-function #'ignore))

;; Don't install anything. Defer execution of BODY
;;(elpaca nil (message "deferred"))
;; End elpaca
;; Start evil-mode
;; Expands to: (elpaca evil (use-package evil :demand t))
(use-package evil
  :init
  (setq
   evil-want-integration t
   evil-want-keybinding nil
   evil-vsplit-window-right t
   evil-split-window-below t
   evil-want-C-u-scroll t
   evil-collection-setup-minibuffer t)
  (evil-mode))
(use-package evil-collection
  :after evil
  :config
  (setq evil-collection-media '(dashboard dired ibuffer))
  (setq evil-normal-state-modes
        (append evil-emacs-state-modes
                evil-insert-state-modes
                evil-normal-state-modes
                evil-motion-state-modes))
  (evil-collection-init)
  (evil-set-undo-system 'undo-redo)
  (add-hook 'window-size-change-functions #'update-scroll-keybinding))
;; End evil-mode
;; Start general-keybindings
(defun print-current-directory ()
  "Print the current directory in the minibuffer."
  (interactive)
  (message "Current directory: %s" default-directory))

(defun update-scroll-keybinding (&optional frame)
  "Update keybindings in evil-normal-state-map and evil-visual-state-map based on the current window height."
  (interactive)
  ;; Calculate the value based on the current window height
  (let ((x-value (ceiling (/ (float (window-height)) (* 2.2 1.2)))))
    ;; Define the keybindings using the calculated value and 'k'
    (define-key evil-normal-state-map (kbd "C-u") (kbd (format "%dk" x-value)))
    (define-key evil-visual-state-map (kbd "C-u") (kbd (format "%dk" x-value)))
    (define-key evil-normal-state-map (kbd "C-d") (kbd (format "%dj" x-value)))
    (define-key evil-visual-state-map (kbd "C-d") (kbd (format "%dj" x-value))))
)

(defun toggle-shell()
  (interactive)
  (if (string= (buffer-name) "*shell*")
      (switch-to-buffer (other-buffer))
    (shell)))

(use-package general
  :config
  (general-evil-setup)

  ;; Leader key
  (general-create-definer dw/leader-keys
    :states '(normal insert visual emacs)
    :keymaps 'override
    :prefix  "SPC"
    :global-prefix "M-SPC")

  (dw/leader-keys
    "q" '(kill-this-buffer :wk "Quit")
    "Q" '(kill-this-buffer :wk "Quit"))

  (dw/leader-keys
    "SPC" '(:ignore t :wk "2nd layer"))

  (dw/leader-keys
    "." '(:ignore t :wk "Current directory")
    ". d" '(print-current-directory :wk "Prints the current directory")
    ". r" '(update-scroll-keybinding :wk "Sets the scrolling settings by window size")
    ". n" '(centered-window-mode :wk "Sets the centered window mode"))

  (dw/leader-keys
    "f" '(:ignore t :wk "Filesystem")
    "f s" '(save-buffer :wk "Save file")
    "f S" '(save-some-buffers :wk "Save all files")
    "f f" '(find-file :wk "Find file")
    "f t" '(find-grep-dired :wk "Find text")
    "f r" '(counsel-recentf :wk "Find recent files")
    "f c" '((lambda () (interactive) (dired "~/.config/emacs")) :wk "Edit emacs config"))

  (dw/leader-keys
    "e" '(:ignore t :wk "Evaluate")    
    "e b" '(eval-buffer :wk "Evaluate elisp in buffer")
    "e d" '(eval-defun :wk "Evaluate defun containing or after point")
    "e e" '(eval-expression :wk "Evaluate and elisp expression")
    "e l" '(eval-last-sexp :wk "Evaluate elisp expression before point")
    "e r" '(eval-region :wk "Evaluate elisp in region"))

  (dw/leader-keys
    "h" '(:ignore t :wk "Help")
    "h d" '(:ignore :wk "Describe")
    "h d f" '(describe-function :wk "Function")
    "h d F" '(describe-face :wk "Face")
    "h d m" '(describe-mode :wk "Mode")
    "h d v" '(describe-variable :wk "Variable")
    "h d k" '(describe-key :wk "Mode")
    "h i" '(info :wk "Open manual")
    "h a" '(:ignore t :wk "Apropos")
    "h a a" '(apropos :wk "Apropos")
    "h a c" '(apropos-command :wk "Command")
    "h a l" '(apropos-library :wk "Library")
    "h a u" '(apropos-user-option :wk "User option")
    "h a v" '(apropos-value :wk "Value")
    "h l" '(:ignore t :wk "Load")
    ;; Won't work for some reason
    ;; "h l t" '(load-theme :wk "Theme")
    "h r" '(:ignore t :wk "Reload")
    "h r t" '(load-selected-theme :wk "Theme" )
    "h r r" '(restart-emacs :wk "Emacs config"))

  (dw/leader-keys 
    "t" '(:ignore t :wk "Toggle")
    "t l" '(display-line-numbers-mode :wk "Toggle line numbers")
    "t t" '(visual-line-mode :wk "Toggle truncated lines")
    "t i" '(org-toggle-inline-images :wk "Toggle inline images"))

  (dw/leader-keys
    "w" '(:ignore t :wk "Window/Buffer management")
     ;; Buffer
    "w b" '(switch-to-buffer :wk "Switch buffer")
    "w i" '(ibuffer :wk "Ibuffer")
    "w C" '(kill-this-buffer :wk "Kill this buffer")
    "w n" '(next-buffer :wk "Next buffer")
    "w p" '(previous-buffer :wk "Previous buffer")
    "w r" '(revert-buffer :wk "Reload buffer")
    ;; Window splits
    "w c" '(evil-window-delete :wk "Close window")
    "w n" '(evil-window-new :wk "New window")
    "w s" '(evil-window-split :wk "Horizontal split window")
    "w v" '(evil-window-vsplit :wk "Vertical split window")
    ;; Window motions
    "w h" '(evil-window-left :wk "Window left")
    "w j" '(evil-window-down :wk "Window down")
    "w k" '(evil-window-up :wk "Window up")
    "w l" '(evil-window-right :wk "Window right")
    "w w" '(evil-window-next :wk "Goto next window")
    ;; Move Windows
    "w H" '(buf-move-left :wk "Buffer move left")
    "w J" '(buf-move-down :wk "Buffer move down")
    "w K" '(buf-move-up :wk "Buffer move up")
    "w L" '(buf-move-right :wk "Buffer move right"))

  (dw/leader-keys
    "d" '(:ignore t :wk "Dired")
    "d d" '(dired :wk "Open dired")
    "d j" '(dired-jump :wk "Dired jump to current")
    "d n" '(neotree-dir :wk "Open directory in neotree")
    "d p" '(peep-dired :wk "Peep-dired"))

  (dw/leader-keys 
    "o" '(:ignore t :wk "Org mode")
    "o l" '(:ignore t :wk "Link")
    "o l s" '(org-store-link :wk "Store link")
    "o l i" '(org-insert-link :wk "Insert link"))

  ;; g
  (general-create-definer dw/g-keys
     :states '(normal insert visual emacs)
     :keymaps 'override
     :prefix  "g"
     :global-prefix "M-g")

  ;; Comment line
  (dw/g-keys "c" '(comment-line :wk "Comment"))

  ;; semicollon
  (general-create-definer dw/semicollon-keys
     :states '(normal insert visual emacs)
     :keymaps 'override
     :prefix  ";"
     :global-prefix "M-;")

  (dw/semicollon-keys
    "q" '(kill-this-buffer :wk "Kill this buffer")
    "e" '(treemacs-select-window :wk "Selects treemacs")
    "E" '(treemacs :wk "Opens treemacs")
    "z" '(kill-emacs :wk "Reload buffer"))

  ;; Ctrl keys
  (define-key evil-normal-state-map (kbd "C-t") 'toggle-shell)

  ;; Makes Escape quit prompts (Minibuffer Escape)
  (global-set-key [escape] 'keyboard-escape-quit)

  ;; Basic movement bindings
  (define-key evil-normal-state-map (kbd "H") 'beginning-of-line-text)
  (define-key evil-visual-state-map (kbd "H") 'beginning-of-line-text)
  (define-key evil-normal-state-map (kbd "L") 'end-of-line)
  (define-key evil-visual-state-map (kbd "L") 'end-of-line)
  (define-key evil-normal-state-map (kbd "K") 'evil-backward-paragraph)
  (define-key evil-visual-state-map (kbd "K") 'evil-backward-paragraph)
  (define-key evil-normal-state-map (kbd "J") 'evil-forward-paragraph)
  (define-key evil-visual-state-map (kbd "J") 'evil-forward-paragraph)
)

(defun print-current-directory ()
  "Print the current directory in the minibuffer."
  (interactive)
  (message "Current directory: %s" default-directory))

(defun update-scroll-keybinding (&optional frame)
       "Update keybindings in evil-normal-state-map and evil-visual-state-map based on the current window height."
       (interactive)
       ;; Calculate the value based on the current window height
       (let ((x-value (ceiling (/ (float (window-height)) (* 2.2 1.2)))))
          ;; Define the keybindings using the calculated value and 'k'
          (define-key evil-normal-state-map (kbd "C-u") (kbd (format "%dk" x-value)))
          (define-key evil-visual-state-map (kbd "C-u") (kbd (format "%dk" x-value)))
          (define-key evil-normal-state-map (kbd "C-d") (kbd (format "%dj" x-value)))
          (define-key evil-visual-state-map (kbd "C-d") (kbd (format "%dj" x-value)))
   )
)

(add-hook 'window-size-change-functions #'update-scroll-keybinding)

(defun toggle-shell()
  (interactive)
  (if (string= (buffer-name) "*shell*")
      (switch-to-buffer (other-buffer))
    (shell)))
;; End general-keybindings
;; Start nerd-icons
(use-package nerd-icons
  :if (display-graphic-p))

(use-package nerd-icons-dired
  :hook (dired-mode . (lambda () (nerd-icons-dired-mode t))))

(use-package nerd-icons-ibuffer
  :hook (ibuffer-mode . nerd-icons-ibuffer-mode))
;; End nerd-icons
;; Start buffer-move
(require 'windmove)

;;;###autoload
(defun buf-move-up ()
  "Swap the current buffer and the buffer above the split.
If there is no split, ie now window above the current one, an
error is signaled."
;;  "Switches between the current buffer, and the buffer above the
;;  split, if possible."
  (interactive)
  (let* ((other-win (windmove-find-other-window 'up))
	 (buf-this-buf (window-buffer (selected-window))))
    (if (null other-win)
        (error "No window above this one")
      ;; swap top with this one
      (set-window-buffer (selected-window) (window-buffer other-win))
      ;; move this one to top
      (set-window-buffer other-win buf-this-buf)
      (select-window other-win))))

;;;###autoload
(defun buf-move-down ()
"Swap the current buffer and the buffer under the split.
If there is no split, ie now window under the current one, an
error is signaled."
  (interactive)
  (let* ((other-win (windmove-find-other-window 'down))
	 (buf-this-buf (window-buffer (selected-window))))
    (if (or (null other-win) 
            (string-match "^ \\*Minibuf" (buffer-name (window-buffer other-win))))
        (error "No window under this one")
      ;; swap top with this one
      (set-window-buffer (selected-window) (window-buffer other-win))
      ;; move this one to top
      (set-window-buffer other-win buf-this-buf)
      (select-window other-win))))

;;;###autoload
(defun buf-move-left ()
"Swap the current buffer and the buffer on the left of the split.
If there is no split, ie now window on the left of the current
one, an error is signaled."
  (interactive)
  (let* ((other-win (windmove-find-other-window 'left))
	 (buf-this-buf (window-buffer (selected-window))))
    (if (null other-win)
        (error "No left split")
      ;; swap top with this one
      (set-window-buffer (selected-window) (window-buffer other-win))
      ;; move this one to top
      (set-window-buffer other-win buf-this-buf)
      (select-window other-win))))

;;;###autoload
(defun buf-move-right ()
"Swap the current buffer and the buffer on the right of the split.
If there is no split, ie now window on the right of the current
one, an error is signaled."
  (interactive)
  (let* ((other-win (windmove-find-other-window 'right))
	 (buf-this-buf (window-buffer (selected-window))))
    (if (null other-win)
        (error "No right split")
      ;; swap top with this one
      (set-window-buffer (selected-window) (window-buffer other-win))
      ;; move this one to top
      (set-window-buffer other-win buf-this-buf)
      (select-window other-win))))
;; End buffer-move
;; Start backup-file
;; Not working
;; (setq backup-directory-alist `(("." . "~/.config/emacs/backups")))

(setq backup-by-copying t)

(setq delete-old-versions t
 kept-new-versions 6
 kept-old-versions 2
 version-control t)
;; End backup-file
;; Start centered-window-mode
(use-package centered-window)
;; End centered-window-mode
;; Start cursor
(setq blink-cursor-mode nil)
;; End cursor
;; Start company-mode
(use-package company
  :after lsp-mode
  :hook ((lsp-mode . company-mode)
         (eglot . company-mode))
  :bind (:map company-active-map
         ("<tab>" . company-complete-selection))
        (:map lsp-mode-map
         ("<tab>" . company-indent-or-complete-common))
  :custom
  (company-minimum-prefix-length 1)
  (company-idle-delay 0.0))

(use-package company-box
  :hook (company-mode . company-box-mode))
;; End company-mode
;; Start dashboard
(use-package dashboard
  :ensure t
  :config
  (add-hook 'elpaca-after-init-hook #'dashboard-insert-startupify-lists)
  (add-hook 'elpaca-after-init-hook #'dashboard-initialize)
  (dashboard-setup-startup-hook)
  (setq initial-buffer-choice (lambda () (get-buffer-create "*dashboard*")))
)
;; End dashboard
;; Start drag-stuff
(use-package drag-stuff
  :init
  (drag-stuff-global-mode 1)
  (drag-stuff-define-keys))
;; End drag-stuff
;; Start diminish
(use-package diminish)
;; End diminish
;; Start dired
(use-package dired-open
  :config
    (setq dired-open-extensions '(("mkv" . "mpv")
                                  ("mp4" . "mpv"))))
(use-package peep-dired
  :after dired
  :hook (evil-normalize-keymaps . peep-dired-hook)
  :config
    (evil-define-key 'normal dired-mode-map (kbd "h") 'dired-up-directory)
    (evil-define-key 'normal dired-mode-map (kbd "l") 'dired-open-file) ; use dired-find-file instead if not using dired-open package
    (evil-define-key 'normal peep-dired-mode-map (kbd "j") 'peep-dired-next-file)
    (evil-define-key 'normal peep-dired-mode-map (kbd "k") 'peep-dired-prev-file)
)
;; End dired
;; Start annoying-beeping
(setq visible-bell 1)
(set-message-beep 'silent)
;; End annoying-beeping
;; Start fonts
(set-face-attribute 'default nil
  :font "IBM Plex Mono"
  :height 90
  :weight 'medium)
(set-face-attribute 'variable-pitch nil
  :font "IBM Plex Mono"
  :height 100
  :weight 'medium)
(set-face-attribute 'fixed-pitch nil
  :font "IBM Plex Mono"
  :height 90
  :weight 'medium)
;; Makes commented text and keywords italics.
;; This is working in emacsclient but not emacs.
;; Your font must have an italic face available.
(set-face-attribute 'font-lock-comment-face nil
  :slant 'italic)
(set-face-attribute 'font-lock-keyword-face nil
  :slant 'italic)

;; This sets the default font on all graphical frames created after restarting Emacs.
;; Does the same thing as 'set-face-attribute default' above, but emacsclient fonts
;; are not right unless I also add this method of setting the default font.
(add-to-list 'default-frame-alist '(font . "IBM Plex Mono"))

;; Uncomment the following line if line spacing needs adjusting.
(setq-default line-spacing 0.12)

(global-set-key (kbd "C-=") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
(global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
(global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)
;; End fonts
;; Start flycheck
(use-package flycheck
  :ensure t
  :defer t
  :diminish
  :init (global-flycheck-mode))
;; End flycheck
;; Start git
;;(use-package magit
;;  :commands magit-status)

;; Set status to only staging, for performance reasons
(define-derived-mode magit-staging-mode magit-status-mode "Magit staging"
  "Mode for showing staged and unstaged changes."
  :group 'magit-status)
(defun magit-staging-refresh-buffer ()
  (magit-insert-section (status)
      (magit-insert-untracked-files)
      (magit-insert-unstaged-changes)
      (magit-insert-staged-changes)))
(defun magit-staging ()
  (interactive)
  (magit-mode-setup #'magit-staging-mode))

(use-package diff-hl
  :hook ((magit-pre-refresh-hook . diff-hl-magit-pre-refresh)
         (magit-post-refresh-hook . diff-hl-magit-post-refresh))
  :init (global-diff-hl-mode))
;; End git
;; Start gui-tweaks
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(set-fringe-mode 10)

(defun toggle-line-numbers ()
  (global-display-line-numbers-mode 1)
  (setq display-line-numbers-type 'relative))
(defun toggle-truncated-lines ()
  (global-visual-line-mode t))
(toggle-line-numbers)
(toggle-truncated-lines)

; Scroll by one line when moving off the screen by 1 line
  (setq scroll-conservatively 101)
  (defun update-scroll-margin (&optional frame)
	"Update scroll-margin based on the current window height."
	(interactive)
	(setq scroll-margin
	(ceiling (/ (float (window-height))
		  (* 3.5 1.2)))))

(add-hook 'window-size-change-functions #'update-scroll-margin)

(set-frame-parameter nil 'alpha-background 70)
(add-to-list 'default-frame-alist '(alpha-background . 90))
;; End gui-tweaks
;; Start grep
(setq find-program (expand-file-name "shims/find.exe" user-emacs-directory))
(use-package rg
  :config
  (rg-enable-default-bindings))
;; End grep
;; Start hook-daemon-and-client
(add-hook 'after-make-frame-functions
  (lambda (frame)
      (with-selected-frame frame
         (update-scroll-keybinding)
         (load-selected-theme)
         (toggle-line-numbers)
         (toggle-truncated-lines))))
;; End hook-daemon-and-client
;; Start image
;;(setq image-animate-loop nil)
(setq org-startup-with-inline-images t)
;; End image
;; Start ivy-counsel
(use-package counsel
  :after ivy
  :config (counsel-mode))

(use-package ivy
  :bind
  ;; ivy-resume resumes the last Ivy-based completion.
  (("C-c C-r" . ivy-resume)
   ("C-x B" . ivy-switch-buffer-other-window))
  :custom
  (setq ivy-use-virtual-buffers t)
  (setq ivy-count-format "(%d/%d) ")
  (setq enable-recursive-minibuffers t)
  :config
  (ivy-mode))

(use-package all-the-icons-ivy-rich
  :ensure t
  :init (all-the-icons-ivy-rich-mode 1))

(use-package ivy-rich
  :after ivy
  :ensure t
  :init (ivy-rich-mode 1) ;; this gets us descriptions in M-x.
  :custom
  (ivy-virtual-abbreviate 'full
   ivy-rich-switch-buffer-align-virtual-buffer t
   ivy-rich-path-style 'abbrev)
  :config
  (ivy-set-display-transformer 'ivy-switch-buffer
                               'ivy-rich-switch-buffer-transformer))
;; End ivy-counsel
;; Start lsp


(defvar zig-ts-mode-initialized nil
  "Flag to track initialization of zig-ts-mode.")

(defun my-zig-ts-mode-init ()
  "Initialize zig-ts-mode and LSP if not already initialized."
  (unless zig-ts-mode-initialized
    (setq zig-ts-mode-initialized t)
    (zig-ts-mode)
    (lsp))
  (when zig-ts-mode-initialized
    (lsp)))

  (use-package lsp-mode
    :init
    (setq lsp-keymap-prefix "C-c l")
    :hook ((zig-ts-mode . my-zig-ts-mode-init)
           (lsp-mode . lsp-enable-which-key-integration))
    :commands (lsp lsp-deferred)
    :config
    (add-to-list 'lsp-language-id-configuration '(zig-ts-mode . "zig"))
    (add-hook 'go-mode-hook 'lsp-deferred))

(use-package go-mode
   :mode "\\.go\\'"
 )

  ;; (use-package go-ts-mode
  ;;   :hook
  ;;   (go-ts-mode . lsp-deferred)
  ;;   (go-ts-mode . go-format-on-save-mode)
  ;;   :init
  ;;   (add-to-list 'treesit-language-source-alist '(go "https://github.com/tree-sitter/tree-sitter-go"))
  ;;   (add-to-list 'treesit-language-source-alist '(gomod "https://github.com/camdencheek/tree-sitter-go-mod"))
  ;;   ;; (dolist (lang '(go gomod)) (treesit-install-language-grammar lang))
  ;;   (add-to-list 'auto-mode-alist '("\\.go\\'" . go-ts-mode))
  ;;   (add-to-list 'auto-mode-alist '("/go\\.mod\\'" . go-mod-ts-mode))
  ;;   )

;; (use-package typescript-mode
;;   :mode "\\.ts\\'"
;;   :hook (typescript-mode . lsp-deferred)
;;   :hook (typescript-ts-mode . lsp-deferred)
;;   :config
;;   (setq typescript-indent-level 2))

;; (use-package python-mode
;;   :ensure t
;;   :hook (python-mode . lsp-deferred)
;;   :custom
;;   ;; NOTE: Set these if Python 3 is called "python3" on your system!
;;   ;; (python-shell-interpreter "python3")
;;   ;; (dap-python-executable "python3")
;;   (dap-python-debugger 'debugpy)
;;   :config
;;   (require 'dap-python))

(use-package zig-mode
  :ensure (zig-mode :host github :repo "nanzhong/zig-mode" :branch "tree-sitter")
  :mode (("\\.zig\\'" . zig-ts-mode)
         ("\\.zon\\'" . zig-ts-mode))
  :hook (zig-ts-mode . (lambda () (setq treesit-font-lock-level 4))))

;; (use-package zig-mode
;;    :hook (zig-mode . lsp-deferred)
;;    :mode "\\.zig\\'")

(use-package nix-mode
  :mode "\\.nix\\'")

(use-package dap-mode
  ;; Uncomment the config below if you want all UI panes to be hidden by default!
  ;; :custom
  ;; (lsp-enable-dap-auto-configure nil)
  ;; :config
  ;; (dap-ui-mode 1)
  :commands dap-debug
  :config
  ;; Set up Node debugging
  (require 'dap-node)
  (dap-node-setup) ;; Automatically installs Node debug adapter if needed
  ;;:bind 
  ;;(("<f7>" . dap-step-in)
  ;; ("<f8>" . dap-next)
  ;; ("<f9>" . dap-continue))

  ;; Bind `C-c l d` to `dap-hydra` for easy access
  (general-define-key
    :keymaps 'lsp-mode-map
    :prefix lsp-keymap-prefix
    "d" '(dap-hydra t :wk "debugger")))

  ;; (use-package dap-mode
  ;;    :config
  ;;    (dap-auto-configure-mode)
  ;;    :bind 
  ;;    (("<f7>" . dap-step-in)
  ;;     ("<f8>" . dap-next)
  ;;     ("<f9>" . dap-continue)))
;; End lsp
;; Start org-mode
(use-package toc-org
    :commands toc-org-enable
    :init (add-hook 'org-mode-hook 'toc-org-enable))

(add-hook 'org-mode-hook 'org-indent-mode)
(use-package org-superstar
  :after org
  :hook (org-mode . org-superstar-mode))

(use-package ob-mermaid
  :after org)

(electric-indent-mode -1)
(setq org-edit-src-content-indentation 2)

(require 'org-tempo)

(setq org-cycle-inline-images-display t)
;; End org-mode
;; Start rainbow-mode
(use-package rainbow-mode
  :diminish
  :hook 
  ((org-mode prog-mode) . rainbow-mode))
;; End rainbow-mode
;; Start rainbow-delimiters
(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))
;; End rainbow-delimiters
;; Start reload-emacs
(defun reload-init-file ()
  (interactive)
  (load-file user-init-file)
  (load-file user-init-file))
;; End reload-emacs
;; Start recentf
(setq recentf-max-saved-items 1000)
;; End recentf
;; Start space-only
(indent-tabs-mode nil)
;; End space-only
;; Start neotree
;; Won't work
;; (use-package neotree)
;; End neotree
;; Start modeline
(use-package doom-modeline
  :init (doom-modeline-mode 1)
  :custom
  (doom-modeline-height 25)     ;; Sets modeline height
  (doom-modeline-bar-width 5)   ;; Sets right bar width
  (doom-modeline-persp-name t)  ;; Adds perspective name to modeline
  (doom-modeline-persp-icon t)) ;; Adds folder icon next to persp name
;; End modeline
;; Start tree-sitter
(defun treesit-install-all()
  (interactive)
  (mapc #'treesit-install-language-grammar (mapcar #'car treesit-language-source-alist))
)

(setq treesit-language-source-alist
 '((bash "https://github.com/tree-sitter/tree-sitter-bash")
   (cmake "https://github.com/uyha/tree-sitter-cmake")
   (css "https://github.com/tree-sitter/tree-sitter-css")
   (elisp "https://github.com/Wilfred/tree-sitter-elisp")
   (go "https://github.com/tree-sitter/tree-sitter-go")
   (c "https://github.com/tree-sitter/tree-sitter-c")
   (cpp "https://github.com/tree-sitter/tree-sitter-cpp")
   (html "https://github.com/tree-sitter/tree-sitter-html")
   (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
   (json "https://github.com/tree-sitter/tree-sitter-json")
   (make "https://github.com/alemuller/tree-sitter-make")
   (markdown "https://github.com/ikatyang/tree-sitter-markdown")
   (python "https://github.com/tree-sitter/tree-sitter-python")
   (toml "https://github.com/tree-sitter/tree-sitter-toml")
   (zig "https://github.com/maxxnino/tree-sitter-zig")
   (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
   (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
   (yaml "https://github.com/ikatyang/tree-sitter-yaml")
   (zig "https://github.com/maxxnino/tree-sitter-zig")
   (nix "https://github.com/nix-community/tree-sitter-nix")))

(setq major-mode-remap-alist
 '((yaml-mode . yaml-ts-mode)
   (bash-mode . bash-ts-mode)
   (js2-mode . js-ts-mode)
   (typescript-mode . typescript-ts-mode)
   (json-mode . json-ts-mode)
   (css-mode . css-ts-mode)
   (python-mode . python-ts-mode)))

(use-package nix-ts-mode
  :mode "\\.nix\\'")
;; End tree-sitter
;; Start treemacs
(use-package treemacs
  :ensure t
  :defer t
  :init
  (with-eval-after-load 'winum
    (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
  :config
  (progn
    (setq treemacs-collapse-dirs                   (if treemacs-python-executable 3 0)
          treemacs-deferred-git-apply-delay        0.5
          treemacs-directory-name-transformer      #'identity
          treemacs-display-in-side-window          t
          treemacs-eldoc-display                   'simple
          treemacs-file-event-delay                2000
          treemacs-file-extension-regex            treemacs-last-period-regex-value
          treemacs-file-follow-delay               0.2
          treemacs-file-name-transformer           #'identity
          treemacs-follow-after-init               t
          treemacs-expand-after-init               t
          treemacs-find-workspace-method           'find-for-file-or-pick-first
          treemacs-git-command-pipe                ""
          treemacs-goto-tag-strategy               'refetch-index
          treemacs-header-scroll-indicators        '(nil . "^^^^^^")
          treemacs-hide-dot-git-directory          t
          treemacs-indentation                     2
          treemacs-indentation-string              " "
          treemacs-is-never-other-window           nil
          treemacs-max-git-entries                 5000
          treemacs-missing-project-action          'ask
          treemacs-move-forward-on-expand          nil
          treemacs-no-png-images                   nil
          treemacs-no-delete-other-windows         t
          treemacs-project-follow-cleanup          nil
          treemacs-persist-file                    (expand-file-name ".cache/treemacs-persist" user-emacs-directory)
          treemacs-position                        'left
          treemacs-read-string-input               'from-child-frame
          treemacs-recenter-distance               0.1
          treemacs-recenter-after-file-follow      nil
          treemacs-recenter-after-tag-follow       nil
          treemacs-recenter-after-project-jump     'always
          treemacs-recenter-after-project-expand   'on-distance
          treemacs-litter-directories              '("/node_modules" "/.venv" "/.cask")
          treemacs-project-follow-into-home        nil
          treemacs-show-cursor                     nil
          treemacs-show-hidden-files               t
          treemacs-silent-filewatch                nil
          treemacs-silent-refresh                  nil
          treemacs-sorting                         'alphabetic-asc
          treemacs-select-when-already-in-treemacs 'move-back
          treemacs-space-between-root-nodes        t
          treemacs-tag-follow-cleanup              t
          treemacs-tag-follow-delay                1.5
          treemacs-text-scale                      nil
          treemacs-user-mode-line-format           nil
          treemacs-user-header-line-format         nil
          treemacs-wide-toggle-width               70
          treemacs-width                           35
          treemacs-width-increment                 1
          treemacs-width-is-initially-locked       t
          treemacs-workspace-switch-cleanup        nil)

    ;; The default width and height of the icons is 22 pixels. If you are
    ;; using a Hi-DPI display, uncomment this to double the icon size.
    ;;(treemacs-resize-icons 44)

    (treemacs-follow-mode t)
    (treemacs-filewatch-mode t)
    (treemacs-fringe-indicator-mode 'always)
    (when treemacs-python-executable
      (treemacs-git-commit-diff-mode t))

    (pcase (cons (not (null (executable-find "git")))
                 (not (null treemacs-python-executable)))
      (`(t . t)
       (treemacs-git-mode 'deferred))
      (`(t . _)
       (treemacs-git-mode 'simple)))

    (treemacs-hide-gitignored-files-mode nil))
  :bind
  (:map global-map
        ("M-0"       . treemacs-select-window)
        ("C-x t 1"   . treemacs-delete-other-windows)
        ("C-x t t"   . treemacs)
        ("C-x t d"   . treemacs-select-directory)
        ("C-x t B"   . treemacs-bookmark)
        ("C-x t C-t" . treemacs-find-file)
        ("C-x t M-t" . treemacs-find-tag)))

(use-package treemacs-evil
  :after (treemacs evil)
  :ensure t)

(use-package treemacs-icons-dired
  :hook (dired-mode . treemacs-icons-dired-enable-once)
  :ensure t)

(use-package treemacs-magit
  :after (treemacs magit)
  :ensure t)
;; End treemacs
;; Start theme
(defun load-selected-theme ()

  (interactive)
  (load-theme 'kanagawa t)
  ;; (autothemer--current-theme 'kanagawa)

)

(use-package catppuccin-theme)

;; (use-package kanagawa-theme)

(use-package autothemer 
 :init
 (add-to-list 'custom-theme-load-path "~/.config/emacs/themes/")
 (load-selected-theme))

(use-package doom-themes)
;; End theme
;; Start which-key
(use-package which-key
  :init
    (which-key-mode 1)
  :diminish
  :config
  (setq which-key-side-window-location 'bottom
     which-key-sort-order #'which-key-key-order-alpha
     which-key-allow-imprecise-window-fit nil
     which-key-sort-uppercase-first nil
     which-key-add-column-padding 1
     which-key-max-display-columns nil
     which-key-min-display-lines 6
     which-key-side-window-slot -10
     which-key-side-window-max-height 0.25
     which-key-idle-delay 0.2
     which-key-max-description-length 25
     which-key-allow-imprecise-window-fit nil
     which-key-separator " > " ))
;; End which-key
;; Start yasnippet
(use-package yasnippet-snippets
  :hook (prog-mode . yas-minor-mode))
;; End yasnippet
;; Start runtime-performance
;; Make gc pauses faster by decreasing the threshold.
(setq gc-cons-threshold (* 2 1000 1000))
;; Increase the amount of data which Emacs reads from the process
(setq read-process-output-max (* 1024 1024)) ;; 1mb
;; End runtime-performance
